//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomersProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteris
    {
        public Musteris()
        {
            this.Faturas = new HashSet<Faturas>();
        }
    
        public int ID { get; set; }
        public string UNVAN { get; set; }
    
        public virtual ICollection<Faturas> Faturas { get; set; }
    }
}
