//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomersProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faturas
    {
        public int ID { get; set; }
        public int MUSTERI_ID { get; set; }
        public string FATURA_TARIHI { get; set; }
        public double FATURA_TUTARI { get; set; }
        public string ODEME_TARIHI { get; set; }
    
        public virtual Musteris Musteris { get; set; }
    }
}
